name: Minify Files

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Auto Minify
        uses: nizarmah/auto-minify@master
        with:
          directory: 'res'
          output: 'min'

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: 'min'
          commit_message: 'Github Action: Auto Minified JS and CSS files'
          branch: ${{ github.ref }}
